name = "hackerel"
main = "src/index.ts"
compatibility_date = "2024-12-08"

[[d1_databases]]
binding = "DB"
database_name = "hackerel"
database_id = "7313cf48-708c-4b14-94d3-8c80debc9bd3"

[observability]
enabled = true
head_sampling_rate = 1

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
